name: Build and Release

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Package Electron App
        run: npm run package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deltavision-${{ matrix.platform }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/**/*.exe
            dist/**/*.dmg
            dist/**/*.AppImage
            dist/**/*.deb
            dist/**/*.rpm
          if-no-files-found: warn

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Generate Changelog
        id: changelog
        run: |
          # Get the previous tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          # If there's a previous tag, use it to generate changelog
          if [ -n "$PREVIOUS_TAG" ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            echo "## Changes since $PREVIOUS_TAG" >> $GITHUB_OUTPUT
            git log --pretty=format:"- %s (%h)" $PREVIOUS_TAG..HEAD >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            echo "## Initial Release" >> $GITHUB_OUTPUT
            git log --pretty=format:"- %s (%h)" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: DeltaVision v${{ steps.get_version.outputs.VERSION }}
          body: |
            # DeltaVision v${{ steps.get_version.outputs.VERSION }}
            
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Installation
            
            ### Windows
            Download and run the .exe installer
            
            ### macOS
            Download the .dmg file, open it, and drag DeltaVision to your Applications folder
            
            ### Linux
            Download the .AppImage file, make it executable (`chmod +x *.AppImage`), and run it
            
            ## Offline Installation
            For offline environments, download all installers and follow the [offline installation instructions](https://github.com/Journey-West/DeltaVision#offline-installation)
          files: artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build and publish offline package
  offline-package:
    name: Create Offline Package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: offline-package

      - name: Create Offline Package
        run: |
          mkdir -p DeltaVision-Offline-Package
          cp -r offline-package/*/* DeltaVision-Offline-Package/ 2>/dev/null || :
          
          # Create README file
          cat > DeltaVision-Offline-Package/README.txt << EOL
          DeltaVision Offline Installation
          ================================
          
          This package contains standalone installers for DeltaVision that can be used in offline environments.
          
          Installation Instructions:
          -------------------------
          
          Windows:
          1. Double-click the .exe installer file
          2. Follow the installation prompts
          3. Launch DeltaVision from the Start Menu
          
          macOS:
          1. Double-click the .dmg file
          2. Drag DeltaVision to the Applications folder
          3. Launch DeltaVision from the Applications folder
          
          Linux:
          - For Debian/Ubuntu: sudo dpkg -i deltavision_*.deb
          - For Red Hat/Fedora: sudo rpm -i deltavision_*.rpm
          - AppImage: Make the .AppImage file executable (chmod +x *.AppImage) and then run it
          
          For more information, visit: https://github.com/Journey-West/DeltaVision
          EOL
          
          # Create zip archive
          zip -r DeltaVision-Offline-Package.zip DeltaVision-Offline-Package

      - name: Upload Offline Package
        uses: actions/upload-artifact@v4
        with:
          name: DeltaVision-Offline-Package
          path: DeltaVision-Offline-Package.zip
          if-no-files-found: warn

      - name: Get Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Attach Offline Package to Release
        uses: softprops/action-gh-release@v1
        with:
          files: DeltaVision-Offline-Package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
